name: Validation

on: [pull_request, push]

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix: node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn

    - name: Lint Code
      run: yarn lint
